//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public enum bt6DofFlags {
  BT_6DOF_FLAGS_CFM_NORM = 1,
  BT_6DOF_FLAGS_CFM_STOP = 2,
  BT_6DOF_FLAGS_ERP_STOP = 4
}

}
