//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btConvexInternalShapeData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btConvexInternalShapeData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btConvexInternalShapeData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btConvexInternalShapeData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btConvexInternalShapeData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btCollisionShapeData m_collisionShapeData {
    set {
      BulletPINVOKE.btConvexInternalShapeData_m_collisionShapeData_set(swigCPtr, btCollisionShapeData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btConvexInternalShapeData_m_collisionShapeData_get(swigCPtr);
      btCollisionShapeData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btCollisionShapeData(cPtr, false);
      return ret;
    } 
  }

  public btVector3FloatData m_localScaling {
    set {
      BulletPINVOKE.btConvexInternalShapeData_m_localScaling_set(swigCPtr, btVector3FloatData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btConvexInternalShapeData_m_localScaling_get(swigCPtr);
      btVector3FloatData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3FloatData(cPtr, false);
      return ret;
    } 
  }

  public btVector3FloatData m_implicitShapeDimensions {
    set {
      BulletPINVOKE.btConvexInternalShapeData_m_implicitShapeDimensions_set(swigCPtr, btVector3FloatData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btConvexInternalShapeData_m_implicitShapeDimensions_get(swigCPtr);
      btVector3FloatData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3FloatData(cPtr, false);
      return ret;
    } 
  }

  public float m_collisionMargin {
    set {
      BulletPINVOKE.btConvexInternalShapeData_m_collisionMargin_set(swigCPtr, value);
    } 
    get {
      float ret = BulletPINVOKE.btConvexInternalShapeData_m_collisionMargin_get(swigCPtr);
      return ret;
    } 
  }

  public int m_padding {
    set {
      BulletPINVOKE.btConvexInternalShapeData_m_padding_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btConvexInternalShapeData_m_padding_get(swigCPtr);
      return ret;
    } 
  }

  public btConvexInternalShapeData() : this(BulletPINVOKE.new_btConvexInternalShapeData(), true) {
  }

}

}
