//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btCollisionShapeData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btCollisionShapeData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btCollisionShapeData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btCollisionShapeData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btCollisionShapeData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string m_name {
    set {
      BulletPINVOKE.btCollisionShapeData_m_name_set(swigCPtr, value);
    } 
    get {
      string ret = BulletPINVOKE.btCollisionShapeData_m_name_get(swigCPtr);
      return ret;
    } 
  }

  public int m_shapeType {
    set {
      BulletPINVOKE.btCollisionShapeData_m_shapeType_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btCollisionShapeData_m_shapeType_get(swigCPtr);
      return ret;
    } 
  }

  public string m_padding {
    set {
      BulletPINVOKE.btCollisionShapeData_m_padding_set(swigCPtr, value);
    } 
    get {
      string ret = BulletPINVOKE.btCollisionShapeData_m_padding_get(swigCPtr);
      return ret;
    } 
  }

  public btCollisionShapeData() : this(BulletPINVOKE.new_btCollisionShapeData(), true) {
  }

}

}
