//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btCylinderShapeData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btCylinderShapeData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btCylinderShapeData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btCylinderShapeData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btCylinderShapeData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btConvexInternalShapeData m_convexInternalShapeData {
    set {
      BulletPINVOKE.btCylinderShapeData_m_convexInternalShapeData_set(swigCPtr, btConvexInternalShapeData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btCylinderShapeData_m_convexInternalShapeData_get(swigCPtr);
      btConvexInternalShapeData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btConvexInternalShapeData(cPtr, false);
      return ret;
    } 
  }

  public int m_upAxis {
    set {
      BulletPINVOKE.btCylinderShapeData_m_upAxis_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btCylinderShapeData_m_upAxis_get(swigCPtr);
      return ret;
    } 
  }

  public string m_padding {
    set {
      BulletPINVOKE.btCylinderShapeData_m_padding_set(swigCPtr, value);
    } 
    get {
      string ret = BulletPINVOKE.btCylinderShapeData_m_padding_get(swigCPtr);
      return ret;
    } 
  }

  public btCylinderShapeData() : this(BulletPINVOKE.new_btCylinderShapeData(), true) {
  }

}

}
