//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btDefaultMotionState : btMotionState {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal btDefaultMotionState(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BulletPINVOKE.btDefaultMotionState_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btDefaultMotionState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btDefaultMotionState() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btDefaultMotionState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public btTransform m_graphicsWorldTrans {
    set {
      BulletPINVOKE.btDefaultMotionState_m_graphicsWorldTrans_set(swigCPtr, btTransform.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btDefaultMotionState_m_graphicsWorldTrans_get(swigCPtr);
      btTransform ret = (cPtr == global::System.IntPtr.Zero) ? null : new btTransform(cPtr, false);
      return ret;
    } 
  }

  public btTransform m_centerOfMassOffset {
    set {
      BulletPINVOKE.btDefaultMotionState_m_centerOfMassOffset_set(swigCPtr, btTransform.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btDefaultMotionState_m_centerOfMassOffset_get(swigCPtr);
      btTransform ret = (cPtr == global::System.IntPtr.Zero) ? null : new btTransform(cPtr, false);
      return ret;
    } 
  }

  public btTransform m_startWorldTrans {
    set {
      BulletPINVOKE.btDefaultMotionState_m_startWorldTrans_set(swigCPtr, btTransform.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btDefaultMotionState_m_startWorldTrans_get(swigCPtr);
      btTransform ret = (cPtr == global::System.IntPtr.Zero) ? null : new btTransform(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_void m_userPointer {
    set {
      BulletPINVOKE.btDefaultMotionState_m_userPointer_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btDefaultMotionState_m_userPointer_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public btDefaultMotionState(btTransform startTrans, btTransform centerOfMassOffset) : this(BulletPINVOKE.new_btDefaultMotionState__SWIG_0(btTransform.getCPtr(startTrans), btTransform.getCPtr(centerOfMassOffset)), true) {
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btDefaultMotionState(btTransform startTrans) : this(BulletPINVOKE.new_btDefaultMotionState__SWIG_1(btTransform.getCPtr(startTrans)), true) {
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btDefaultMotionState() : this(BulletPINVOKE.new_btDefaultMotionState__SWIG_2(), true) {
  }

  public override void getWorldTransform(btTransform centerOfMassWorldTrans) {
    BulletPINVOKE.btDefaultMotionState_getWorldTransform(swigCPtr, btTransform.getCPtr(centerOfMassWorldTrans));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void setWorldTransform(btTransform centerOfMassWorldTrans) {
    BulletPINVOKE.btDefaultMotionState_setWorldTransform(swigCPtr, btTransform.getCPtr(centerOfMassWorldTrans));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
