//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btDefaultCollisionConstructionInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btDefaultCollisionConstructionInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btDefaultCollisionConstructionInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btDefaultCollisionConstructionInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btDefaultCollisionConstructionInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_btPoolAllocator m_persistentManifoldPool {
    set {
      BulletPINVOKE.btDefaultCollisionConstructionInfo_m_persistentManifoldPool_set(swigCPtr, SWIGTYPE_p_btPoolAllocator.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btDefaultCollisionConstructionInfo_m_persistentManifoldPool_get(swigCPtr);
      SWIGTYPE_p_btPoolAllocator ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btPoolAllocator(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_btPoolAllocator m_collisionAlgorithmPool {
    set {
      BulletPINVOKE.btDefaultCollisionConstructionInfo_m_collisionAlgorithmPool_set(swigCPtr, SWIGTYPE_p_btPoolAllocator.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btDefaultCollisionConstructionInfo_m_collisionAlgorithmPool_get(swigCPtr);
      SWIGTYPE_p_btPoolAllocator ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btPoolAllocator(cPtr, false);
      return ret;
    } 
  }

  public int m_defaultMaxPersistentManifoldPoolSize {
    set {
      BulletPINVOKE.btDefaultCollisionConstructionInfo_m_defaultMaxPersistentManifoldPoolSize_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btDefaultCollisionConstructionInfo_m_defaultMaxPersistentManifoldPoolSize_get(swigCPtr);
      return ret;
    } 
  }

  public int m_defaultMaxCollisionAlgorithmPoolSize {
    set {
      BulletPINVOKE.btDefaultCollisionConstructionInfo_m_defaultMaxCollisionAlgorithmPoolSize_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btDefaultCollisionConstructionInfo_m_defaultMaxCollisionAlgorithmPoolSize_get(swigCPtr);
      return ret;
    } 
  }

  public int m_customCollisionAlgorithmMaxElementSize {
    set {
      BulletPINVOKE.btDefaultCollisionConstructionInfo_m_customCollisionAlgorithmMaxElementSize_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btDefaultCollisionConstructionInfo_m_customCollisionAlgorithmMaxElementSize_get(swigCPtr);
      return ret;
    } 
  }

  public int m_useEpaPenetrationAlgorithm {
    set {
      BulletPINVOKE.btDefaultCollisionConstructionInfo_m_useEpaPenetrationAlgorithm_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btDefaultCollisionConstructionInfo_m_useEpaPenetrationAlgorithm_get(swigCPtr);
      return ret;
    } 
  }

  public btDefaultCollisionConstructionInfo() : this(BulletPINVOKE.new_btDefaultCollisionConstructionInfo(), true) {
  }

}

}
