//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btNullPairCache : btOverlappingPairCache {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal btNullPairCache(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BulletPINVOKE.btNullPairCache_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btNullPairCache obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btNullPairCache() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btNullPairCache(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override btBroadphasePair getOverlappingPairArrayPtr() {
    global::System.IntPtr cPtr = BulletPINVOKE.btNullPairCache_getOverlappingPairArrayPtr__SWIG_0(swigCPtr);
    btBroadphasePair ret = (cPtr == global::System.IntPtr.Zero) ? null : new btBroadphasePair(cPtr, false);
    return ret;
  }

  public override SWIGTYPE_p_btAlignedObjectArrayT_btBroadphasePair_t getOverlappingPairArray() {
    SWIGTYPE_p_btAlignedObjectArrayT_btBroadphasePair_t ret = new SWIGTYPE_p_btAlignedObjectArrayT_btBroadphasePair_t(BulletPINVOKE.btNullPairCache_getOverlappingPairArray(swigCPtr), false);
    return ret;
  }

  public override void cleanOverlappingPair(btBroadphasePair arg0, btDispatcher arg1) {
    BulletPINVOKE.btNullPairCache_cleanOverlappingPair(swigCPtr, btBroadphasePair.getCPtr(arg0), btDispatcher.getCPtr(arg1));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int getNumOverlappingPairs() {
    int ret = BulletPINVOKE.btNullPairCache_getNumOverlappingPairs(swigCPtr);
    return ret;
  }

  public override void cleanProxyFromPairs(btBroadphaseProxy arg0, btDispatcher arg1) {
    BulletPINVOKE.btNullPairCache_cleanProxyFromPairs(swigCPtr, btBroadphaseProxy.getCPtr(arg0), btDispatcher.getCPtr(arg1));
  }

  public override void setOverlapFilterCallback(btOverlapFilterCallback arg0) {
    BulletPINVOKE.btNullPairCache_setOverlapFilterCallback(swigCPtr, btOverlapFilterCallback.getCPtr(arg0));
  }

  public override void processAllOverlappingPairs(btOverlapCallback arg0, btDispatcher arg1) {
    BulletPINVOKE.btNullPairCache_processAllOverlappingPairs(swigCPtr, btOverlapCallback.getCPtr(arg0), btDispatcher.getCPtr(arg1));
  }

  public override btBroadphasePair findPair(btBroadphaseProxy arg0, btBroadphaseProxy arg1) {
    global::System.IntPtr cPtr = BulletPINVOKE.btNullPairCache_findPair(swigCPtr, btBroadphaseProxy.getCPtr(arg0), btBroadphaseProxy.getCPtr(arg1));
    btBroadphasePair ret = (cPtr == global::System.IntPtr.Zero) ? null : new btBroadphasePair(cPtr, false);
    return ret;
  }

  public override bool hasDeferredRemoval() {
    bool ret = BulletPINVOKE.btNullPairCache_hasDeferredRemoval(swigCPtr);
    return ret;
  }

  public override void setInternalGhostPairCallback(btOverlappingPairCallback arg0) {
    BulletPINVOKE.btNullPairCache_setInternalGhostPairCallback(swigCPtr, btOverlappingPairCallback.getCPtr(arg0));
  }

  public override btBroadphasePair addOverlappingPair(btBroadphaseProxy arg0, btBroadphaseProxy arg1) {
    global::System.IntPtr cPtr = BulletPINVOKE.btNullPairCache_addOverlappingPair(swigCPtr, btBroadphaseProxy.getCPtr(arg0), btBroadphaseProxy.getCPtr(arg1));
    btBroadphasePair ret = (cPtr == global::System.IntPtr.Zero) ? null : new btBroadphasePair(cPtr, false);
    return ret;
  }

  public override SWIGTYPE_p_void removeOverlappingPair(btBroadphaseProxy arg0, btBroadphaseProxy arg1, btDispatcher arg2) {
    global::System.IntPtr cPtr = BulletPINVOKE.btNullPairCache_removeOverlappingPair(swigCPtr, btBroadphaseProxy.getCPtr(arg0), btBroadphaseProxy.getCPtr(arg1), btDispatcher.getCPtr(arg2));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public override void removeOverlappingPairsContainingProxy(btBroadphaseProxy arg0, btDispatcher arg1) {
    BulletPINVOKE.btNullPairCache_removeOverlappingPairsContainingProxy(swigCPtr, btBroadphaseProxy.getCPtr(arg0), btDispatcher.getCPtr(arg1));
  }

  public override void sortOverlappingPairs(btDispatcher dispatcher) {
    BulletPINVOKE.btNullPairCache_sortOverlappingPairs(swigCPtr, btDispatcher.getCPtr(dispatcher));
  }

  public btNullPairCache() : this(BulletPINVOKE.new_btNullPairCache(), true) {
  }

}

}
