//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btPoint2PointConstraintDoubleData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btPoint2PointConstraintDoubleData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btPoint2PointConstraintDoubleData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btPoint2PointConstraintDoubleData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btPoint2PointConstraintDoubleData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btTypedConstraintData m_typeConstraintData {
    set {
      BulletPINVOKE.btPoint2PointConstraintDoubleData_m_typeConstraintData_set(swigCPtr, btTypedConstraintData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btPoint2PointConstraintDoubleData_m_typeConstraintData_get(swigCPtr);
      btTypedConstraintData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btTypedConstraintData(cPtr, false);
      return ret;
    } 
  }

  public btVector3DoubleData m_pivotInA {
    set {
      BulletPINVOKE.btPoint2PointConstraintDoubleData_m_pivotInA_set(swigCPtr, btVector3DoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btPoint2PointConstraintDoubleData_m_pivotInA_get(swigCPtr);
      btVector3DoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3DoubleData(cPtr, false);
      return ret;
    } 
  }

  public btVector3DoubleData m_pivotInB {
    set {
      BulletPINVOKE.btPoint2PointConstraintDoubleData_m_pivotInB_set(swigCPtr, btVector3DoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btPoint2PointConstraintDoubleData_m_pivotInB_get(swigCPtr);
      btVector3DoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3DoubleData(cPtr, false);
      return ret;
    } 
  }

  public btPoint2PointConstraintDoubleData() : this(BulletPINVOKE.new_btPoint2PointConstraintDoubleData(), true) {
  }

}

}
