//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btQuaternion : btQuadWord {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal btQuaternion(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BulletPINVOKE.btQuaternion_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btQuaternion obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btQuaternion() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btQuaternion(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public btQuaternion() : this(BulletPINVOKE.new_btQuaternion__SWIG_0(), true) {
  }

  public btQuaternion(float _x, float _y, float _z, float _w) : this(BulletPINVOKE.new_btQuaternion__SWIG_1(_x, _y, _z, _w), true) {
  }

  public btQuaternion(btVector3 _axis, float _angle) : this(BulletPINVOKE.new_btQuaternion__SWIG_2(btVector3.getCPtr(_axis), _angle), true) {
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btQuaternion(float yaw, float pitch, float roll) : this(BulletPINVOKE.new_btQuaternion__SWIG_3(yaw, pitch, roll), true) {
  }

  public void setRotation(btVector3 axis, float _angle) {
    BulletPINVOKE.btQuaternion_setRotation(swigCPtr, btVector3.getCPtr(axis), _angle);
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setEuler(float yaw, float pitch, float roll) {
    BulletPINVOKE.btQuaternion_setEuler(swigCPtr, yaw, pitch, roll);
  }

  public void setEulerZYX(float yaw, float pitch, float roll) {
    BulletPINVOKE.btQuaternion_setEulerZYX(swigCPtr, yaw, pitch, roll);
  }

  public float dot(btQuaternion q) {
    float ret = BulletPINVOKE.btQuaternion_dot(swigCPtr, btQuaternion.getCPtr(q));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float length2() {
    float ret = BulletPINVOKE.btQuaternion_length2(swigCPtr);
    return ret;
  }

  public float length() {
    float ret = BulletPINVOKE.btQuaternion_length(swigCPtr);
    return ret;
  }

  public btQuaternion normalize() {
    btQuaternion ret = new btQuaternion(BulletPINVOKE.btQuaternion_normalize(swigCPtr), false);
    return ret;
  }

  public btQuaternion normalized() {
    btQuaternion ret = new btQuaternion(BulletPINVOKE.btQuaternion_normalized(swigCPtr), true);
    return ret;
  }

  public float angle(btQuaternion q) {
    float ret = BulletPINVOKE.btQuaternion_angle(swigCPtr, btQuaternion.getCPtr(q));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float angleShortestPath(btQuaternion q) {
    float ret = BulletPINVOKE.btQuaternion_angleShortestPath(swigCPtr, btQuaternion.getCPtr(q));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getAngle() {
    float ret = BulletPINVOKE.btQuaternion_getAngle(swigCPtr);
    return ret;
  }

  public float getAngleShortestPath() {
    float ret = BulletPINVOKE.btQuaternion_getAngleShortestPath(swigCPtr);
    return ret;
  }

  public btVector3 getAxis() {
    btVector3 ret = new btVector3(BulletPINVOKE.btQuaternion_getAxis(swigCPtr), true);
    return ret;
  }

  public btQuaternion inverse() {
    btQuaternion ret = new btQuaternion(BulletPINVOKE.btQuaternion_inverse(swigCPtr), true);
    return ret;
  }

  public btQuaternion farthest(btQuaternion qd) {
    btQuaternion ret = new btQuaternion(BulletPINVOKE.btQuaternion_farthest(swigCPtr, btQuaternion.getCPtr(qd)), true);
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btQuaternion nearest(btQuaternion qd) {
    btQuaternion ret = new btQuaternion(BulletPINVOKE.btQuaternion_nearest(swigCPtr, btQuaternion.getCPtr(qd)), true);
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btQuaternion slerp(btQuaternion q, float t) {
    btQuaternion ret = new btQuaternion(BulletPINVOKE.btQuaternion_slerp(swigCPtr, btQuaternion.getCPtr(q), t), true);
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static btQuaternion getIdentity() {
    btQuaternion ret = new btQuaternion(BulletPINVOKE.btQuaternion_getIdentity(), false);
    return ret;
  }

  public float getW() {
    float ret = BulletPINVOKE.btQuaternion_getW(swigCPtr);
    return ret;
  }

}

}
