//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public enum btTypedConstraintType {
  POINT2POINT_CONSTRAINT_TYPE = 3,
  HINGE_CONSTRAINT_TYPE,
  CONETWIST_CONSTRAINT_TYPE,
  D6_CONSTRAINT_TYPE,
  SLIDER_CONSTRAINT_TYPE,
  CONTACT_CONSTRAINT_TYPE,
  D6_SPRING_CONSTRAINT_TYPE,
  GEAR_CONSTRAINT_TYPE,
  FIXED_CONSTRAINT_TYPE,
  MAX_CONSTRAINT_TYPE
}

}
