//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btBroadphasePair : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btBroadphasePair(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btBroadphasePair obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btBroadphasePair() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btBroadphasePair(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btBroadphasePair() : this(BulletPINVOKE.new_btBroadphasePair__SWIG_0(), true) {
  }

  public btBroadphasePair(btBroadphasePair other) : this(BulletPINVOKE.new_btBroadphasePair__SWIG_1(btBroadphasePair.getCPtr(other)), true) {
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btBroadphasePair(btBroadphaseProxy proxy0, btBroadphaseProxy proxy1) : this(BulletPINVOKE.new_btBroadphasePair__SWIG_2(btBroadphaseProxy.getCPtr(proxy0), btBroadphaseProxy.getCPtr(proxy1)), true) {
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btBroadphaseProxy m_pProxy0 {
    set {
      BulletPINVOKE.btBroadphasePair_m_pProxy0_set(swigCPtr, btBroadphaseProxy.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btBroadphasePair_m_pProxy0_get(swigCPtr);
      btBroadphaseProxy ret = (cPtr == global::System.IntPtr.Zero) ? null : new btBroadphaseProxy(cPtr, false);
      return ret;
    } 
  }

  public btBroadphaseProxy m_pProxy1 {
    set {
      BulletPINVOKE.btBroadphasePair_m_pProxy1_set(swigCPtr, btBroadphaseProxy.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btBroadphasePair_m_pProxy1_get(swigCPtr);
      btBroadphaseProxy ret = (cPtr == global::System.IntPtr.Zero) ? null : new btBroadphaseProxy(cPtr, false);
      return ret;
    } 
  }

  public btCollisionAlgorithm m_algorithm {
    set {
      BulletPINVOKE.btBroadphasePair_m_algorithm_set(swigCPtr, btCollisionAlgorithm.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btBroadphasePair_m_algorithm_get(swigCPtr);
      btCollisionAlgorithm ret = (cPtr == global::System.IntPtr.Zero) ? null : new btCollisionAlgorithm(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_void m_internalInfo1 {
    set {
      BulletPINVOKE.btBroadphasePair_m_internalInfo1_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btBroadphasePair_m_internalInfo1_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public int m_internalTmpValue {
    set {
      BulletPINVOKE.btBroadphasePair_m_internalTmpValue_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btBroadphasePair_m_internalTmpValue_get(swigCPtr);
      return ret;
    } 
  }

}

}
