//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btBvhSubtreeInfoData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btBvhSubtreeInfoData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btBvhSubtreeInfoData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btBvhSubtreeInfoData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btBvhSubtreeInfoData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int m_rootNodeIndex {
    set {
      BulletPINVOKE.btBvhSubtreeInfoData_m_rootNodeIndex_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btBvhSubtreeInfoData_m_rootNodeIndex_get(swigCPtr);
      return ret;
    } 
  }

  public int m_subtreeSize {
    set {
      BulletPINVOKE.btBvhSubtreeInfoData_m_subtreeSize_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btBvhSubtreeInfoData_m_subtreeSize_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_short m_quantizedAabbMin {
    set {
      BulletPINVOKE.btBvhSubtreeInfoData_m_quantizedAabbMin_set(swigCPtr, SWIGTYPE_p_unsigned_short.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btBvhSubtreeInfoData_m_quantizedAabbMin_get(swigCPtr);
      SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_short m_quantizedAabbMax {
    set {
      BulletPINVOKE.btBvhSubtreeInfoData_m_quantizedAabbMax_set(swigCPtr, SWIGTYPE_p_unsigned_short.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btBvhSubtreeInfoData_m_quantizedAabbMax_get(swigCPtr);
      SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
      return ret;
    } 
  }

  public btBvhSubtreeInfoData() : this(BulletPINVOKE.new_btBvhSubtreeInfoData(), true) {
  }

}

}
