//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btConeShapeX : btConeShape {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal btConeShapeX(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BulletPINVOKE.btConeShapeX_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btConeShapeX obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btConeShapeX() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btConeShapeX(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public btConeShapeX(float radius, float height) : this(BulletPINVOKE.new_btConeShapeX(radius, height), true) {
  }

  public override btVector3 getAnisotropicRollingFrictionDirection() {
    btVector3 ret = new btVector3(BulletPINVOKE.btConeShapeX_getAnisotropicRollingFrictionDirection(swigCPtr), true);
    return ret;
  }

  public override string getName() {
    string ret = BulletPINVOKE.btConeShapeX_getName(swigCPtr);
    return ret;
  }

}

}
