//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btCompoundShapeData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btCompoundShapeData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btCompoundShapeData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btCompoundShapeData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btCompoundShapeData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btCollisionShapeData m_collisionShapeData {
    set {
      BulletPINVOKE.btCompoundShapeData_m_collisionShapeData_set(swigCPtr, btCollisionShapeData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btCompoundShapeData_m_collisionShapeData_get(swigCPtr);
      btCollisionShapeData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btCollisionShapeData(cPtr, false);
      return ret;
    } 
  }

  public btCompoundShapeChildData m_childShapePtr {
    set {
      BulletPINVOKE.btCompoundShapeData_m_childShapePtr_set(swigCPtr, btCompoundShapeChildData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btCompoundShapeData_m_childShapePtr_get(swigCPtr);
      btCompoundShapeChildData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btCompoundShapeChildData(cPtr, false);
      return ret;
    } 
  }

  public int m_numChildShapes {
    set {
      BulletPINVOKE.btCompoundShapeData_m_numChildShapes_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btCompoundShapeData_m_numChildShapes_get(swigCPtr);
      return ret;
    } 
  }

  public float m_collisionMargin {
    set {
      BulletPINVOKE.btCompoundShapeData_m_collisionMargin_set(swigCPtr, value);
    } 
    get {
      float ret = BulletPINVOKE.btCompoundShapeData_m_collisionMargin_get(swigCPtr);
      return ret;
    } 
  }

  public btCompoundShapeData() : this(BulletPINVOKE.new_btCompoundShapeData(), true) {
  }

}

}
