//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btConstraintRow : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btConstraintRow(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btConstraintRow obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btConstraintRow() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btConstraintRow(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_float m_normal {
    set {
      BulletPINVOKE.btConstraintRow_m_normal_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btConstraintRow_m_normal_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public float m_rhs {
    set {
      BulletPINVOKE.btConstraintRow_m_rhs_set(swigCPtr, value);
    } 
    get {
      float ret = BulletPINVOKE.btConstraintRow_m_rhs_get(swigCPtr);
      return ret;
    } 
  }

  public float m_jacDiagInv {
    set {
      BulletPINVOKE.btConstraintRow_m_jacDiagInv_set(swigCPtr, value);
    } 
    get {
      float ret = BulletPINVOKE.btConstraintRow_m_jacDiagInv_get(swigCPtr);
      return ret;
    } 
  }

  public float m_lowerLimit {
    set {
      BulletPINVOKE.btConstraintRow_m_lowerLimit_set(swigCPtr, value);
    } 
    get {
      float ret = BulletPINVOKE.btConstraintRow_m_lowerLimit_get(swigCPtr);
      return ret;
    } 
  }

  public float m_upperLimit {
    set {
      BulletPINVOKE.btConstraintRow_m_upperLimit_set(swigCPtr, value);
    } 
    get {
      float ret = BulletPINVOKE.btConstraintRow_m_upperLimit_get(swigCPtr);
      return ret;
    } 
  }

  public float m_accumImpulse {
    set {
      BulletPINVOKE.btConstraintRow_m_accumImpulse_set(swigCPtr, value);
    } 
    get {
      float ret = BulletPINVOKE.btConstraintRow_m_accumImpulse_get(swigCPtr);
      return ret;
    } 
  }

  public btConstraintRow() : this(BulletPINVOKE.new_btConstraintRow(), true) {
  }

}

}
