//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btDefaultSerializer : btSerializer {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal btDefaultSerializer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BulletPINVOKE.btDefaultSerializer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btDefaultSerializer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btDefaultSerializer() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btDefaultSerializer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public btDefaultSerializer(int totalSize) : this(BulletPINVOKE.new_btDefaultSerializer__SWIG_0(totalSize), true) {
  }

  public btDefaultSerializer() : this(BulletPINVOKE.new_btDefaultSerializer__SWIG_1(), true) {
  }

  public void writeHeader(SWIGTYPE_p_unsigned_char buffer) {
    BulletPINVOKE.btDefaultSerializer_writeHeader(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(buffer));
  }

  public override void startSerialization() {
    BulletPINVOKE.btDefaultSerializer_startSerialization(swigCPtr);
  }

  public override void finishSerialization() {
    BulletPINVOKE.btDefaultSerializer_finishSerialization(swigCPtr);
  }

  public override SWIGTYPE_p_void getUniquePointer(SWIGTYPE_p_void oldPtr) {
    global::System.IntPtr cPtr = BulletPINVOKE.btDefaultSerializer_getUniquePointer(swigCPtr, SWIGTYPE_p_void.getCPtr(oldPtr));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public override SWIGTYPE_p_unsigned_char getBufferPointer() {
    global::System.IntPtr cPtr = BulletPINVOKE.btDefaultSerializer_getBufferPointer(swigCPtr);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public override int getCurrentBufferSize() {
    int ret = BulletPINVOKE.btDefaultSerializer_getCurrentBufferSize(swigCPtr);
    return ret;
  }

  public override void finalizeChunk(btChunk chunk, string structType, int chunkCode, SWIGTYPE_p_void oldPtr) {
    BulletPINVOKE.btDefaultSerializer_finalizeChunk(swigCPtr, btChunk.getCPtr(chunk), structType, chunkCode, SWIGTYPE_p_void.getCPtr(oldPtr));
  }

  public virtual SWIGTYPE_p_unsigned_char internalAlloc(uint size) {
    global::System.IntPtr cPtr = BulletPINVOKE.btDefaultSerializer_internalAlloc(swigCPtr, size);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public override btChunk allocate(uint size, int numElements) {
    global::System.IntPtr cPtr = BulletPINVOKE.btDefaultSerializer_allocate(swigCPtr, size, numElements);
    btChunk ret = (cPtr == global::System.IntPtr.Zero) ? null : new btChunk(cPtr, false);
    return ret;
  }

  public override string findNameForPointer(SWIGTYPE_p_void ptr) {
    string ret = BulletPINVOKE.btDefaultSerializer_findNameForPointer(swigCPtr, SWIGTYPE_p_void.getCPtr(ptr));
    return ret;
  }

  public override void registerNameForPointer(SWIGTYPE_p_void ptr, string name) {
    BulletPINVOKE.btDefaultSerializer_registerNameForPointer(swigCPtr, SWIGTYPE_p_void.getCPtr(ptr), name);
  }

  public override void serializeName(string name) {
    BulletPINVOKE.btDefaultSerializer_serializeName(swigCPtr, name);
  }

  public override int getSerializationFlags() {
    int ret = BulletPINVOKE.btDefaultSerializer_getSerializationFlags(swigCPtr);
    return ret;
  }

  public override void setSerializationFlags(int flags) {
    BulletPINVOKE.btDefaultSerializer_setSerializationFlags(swigCPtr, flags);
  }

}

}
