//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btDynamicsWorldDoubleData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btDynamicsWorldDoubleData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btDynamicsWorldDoubleData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btDynamicsWorldDoubleData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btDynamicsWorldDoubleData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btContactSolverInfoDoubleData m_solverInfo {
    set {
      BulletPINVOKE.btDynamicsWorldDoubleData_m_solverInfo_set(swigCPtr, btContactSolverInfoDoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btDynamicsWorldDoubleData_m_solverInfo_get(swigCPtr);
      btContactSolverInfoDoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btContactSolverInfoDoubleData(cPtr, false);
      return ret;
    } 
  }

  public btVector3DoubleData m_gravity {
    set {
      BulletPINVOKE.btDynamicsWorldDoubleData_m_gravity_set(swigCPtr, btVector3DoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btDynamicsWorldDoubleData_m_gravity_get(swigCPtr);
      btVector3DoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3DoubleData(cPtr, false);
      return ret;
    } 
  }

  public btDynamicsWorldDoubleData() : this(BulletPINVOKE.new_btDynamicsWorldDoubleData(), true) {
  }

}

}
