//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btOptimizedBvhNodeFloatData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btOptimizedBvhNodeFloatData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btOptimizedBvhNodeFloatData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btOptimizedBvhNodeFloatData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btOptimizedBvhNodeFloatData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btVector3FloatData m_aabbMinOrg {
    set {
      BulletPINVOKE.btOptimizedBvhNodeFloatData_m_aabbMinOrg_set(swigCPtr, btVector3FloatData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btOptimizedBvhNodeFloatData_m_aabbMinOrg_get(swigCPtr);
      btVector3FloatData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3FloatData(cPtr, false);
      return ret;
    } 
  }

  public btVector3FloatData m_aabbMaxOrg {
    set {
      BulletPINVOKE.btOptimizedBvhNodeFloatData_m_aabbMaxOrg_set(swigCPtr, btVector3FloatData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btOptimizedBvhNodeFloatData_m_aabbMaxOrg_get(swigCPtr);
      btVector3FloatData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3FloatData(cPtr, false);
      return ret;
    } 
  }

  public int m_escapeIndex {
    set {
      BulletPINVOKE.btOptimizedBvhNodeFloatData_m_escapeIndex_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btOptimizedBvhNodeFloatData_m_escapeIndex_get(swigCPtr);
      return ret;
    } 
  }

  public int m_subPart {
    set {
      BulletPINVOKE.btOptimizedBvhNodeFloatData_m_subPart_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btOptimizedBvhNodeFloatData_m_subPart_get(swigCPtr);
      return ret;
    } 
  }

  public int m_triangleIndex {
    set {
      BulletPINVOKE.btOptimizedBvhNodeFloatData_m_triangleIndex_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btOptimizedBvhNodeFloatData_m_triangleIndex_get(swigCPtr);
      return ret;
    } 
  }

  public string m_pad {
    set {
      BulletPINVOKE.btOptimizedBvhNodeFloatData_m_pad_set(swigCPtr, value);
    } 
    get {
      string ret = BulletPINVOKE.btOptimizedBvhNodeFloatData_m_pad_get(swigCPtr);
      return ret;
    } 
  }

  public btOptimizedBvhNodeFloatData() : this(BulletPINVOKE.new_btOptimizedBvhNodeFloatData(), true) {
  }

}

}
