//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btPolyhedralConvexShape : btConvexInternalShape {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal btPolyhedralConvexShape(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BulletPINVOKE.btPolyhedralConvexShape_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btPolyhedralConvexShape obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btPolyhedralConvexShape() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btPolyhedralConvexShape(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public virtual bool initializePolyhedralFeatures(int shiftVerticesByMargin) {
    bool ret = BulletPINVOKE.btPolyhedralConvexShape_initializePolyhedralFeatures__SWIG_0(swigCPtr, shiftVerticesByMargin);
    return ret;
  }

  public virtual bool initializePolyhedralFeatures() {
    bool ret = BulletPINVOKE.btPolyhedralConvexShape_initializePolyhedralFeatures__SWIG_1(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_btConvexPolyhedron getConvexPolyhedron() {
    global::System.IntPtr cPtr = BulletPINVOKE.btPolyhedralConvexShape_getConvexPolyhedron(swigCPtr);
    SWIGTYPE_p_btConvexPolyhedron ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btConvexPolyhedron(cPtr, false);
    return ret;
  }

  public override btVector3 localGetSupportingVertexWithoutMargin(btVector3 vec) {
    btVector3 ret = new btVector3(BulletPINVOKE.btPolyhedralConvexShape_localGetSupportingVertexWithoutMargin(swigCPtr, btVector3.getCPtr(vec)), true);
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void batchedUnitVectorGetSupportingVertexWithoutMargin(btVector3 vectors, btVector3 supportVerticesOut, int numVectors) {
    BulletPINVOKE.btPolyhedralConvexShape_batchedUnitVectorGetSupportingVertexWithoutMargin(swigCPtr, btVector3.getCPtr(vectors), btVector3.getCPtr(supportVerticesOut), numVectors);
  }

  public override void calculateLocalInertia(float mass, btVector3 inertia) {
    BulletPINVOKE.btPolyhedralConvexShape_calculateLocalInertia(swigCPtr, mass, btVector3.getCPtr(inertia));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual int getNumVertices() {
    int ret = BulletPINVOKE.btPolyhedralConvexShape_getNumVertices(swigCPtr);
    return ret;
  }

  public virtual int getNumEdges() {
    int ret = BulletPINVOKE.btPolyhedralConvexShape_getNumEdges(swigCPtr);
    return ret;
  }

  public virtual void getEdge(int i, btVector3 pa, btVector3 pb) {
    BulletPINVOKE.btPolyhedralConvexShape_getEdge(swigCPtr, i, btVector3.getCPtr(pa), btVector3.getCPtr(pb));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void getVertex(int i, btVector3 vtx) {
    BulletPINVOKE.btPolyhedralConvexShape_getVertex(swigCPtr, i, btVector3.getCPtr(vtx));
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual int getNumPlanes() {
    int ret = BulletPINVOKE.btPolyhedralConvexShape_getNumPlanes(swigCPtr);
    return ret;
  }

  public virtual void getPlane(btVector3 planeNormal, btVector3 planeSupport, int i) {
    BulletPINVOKE.btPolyhedralConvexShape_getPlane(swigCPtr, btVector3.getCPtr(planeNormal), btVector3.getCPtr(planeSupport), i);
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool isInside(btVector3 pt, float tolerance) {
    bool ret = BulletPINVOKE.btPolyhedralConvexShape_isInside(swigCPtr, btVector3.getCPtr(pt), tolerance);
    if (BulletPINVOKE.SWIGPendingException.Pending) throw BulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
