//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btSerializer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btSerializer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btSerializer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btSerializer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btSerializer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual SWIGTYPE_p_unsigned_char getBufferPointer() {
    global::System.IntPtr cPtr = BulletPINVOKE.btSerializer_getBufferPointer(swigCPtr);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public virtual int getCurrentBufferSize() {
    int ret = BulletPINVOKE.btSerializer_getCurrentBufferSize(swigCPtr);
    return ret;
  }

  public virtual btChunk allocate(uint size, int numElements) {
    global::System.IntPtr cPtr = BulletPINVOKE.btSerializer_allocate(swigCPtr, size, numElements);
    btChunk ret = (cPtr == global::System.IntPtr.Zero) ? null : new btChunk(cPtr, false);
    return ret;
  }

  public virtual void finalizeChunk(btChunk chunk, string structType, int chunkCode, SWIGTYPE_p_void oldPtr) {
    BulletPINVOKE.btSerializer_finalizeChunk(swigCPtr, btChunk.getCPtr(chunk), structType, chunkCode, SWIGTYPE_p_void.getCPtr(oldPtr));
  }

  public virtual SWIGTYPE_p_void findPointer(SWIGTYPE_p_void oldPtr) {
    global::System.IntPtr cPtr = BulletPINVOKE.btSerializer_findPointer(swigCPtr, SWIGTYPE_p_void.getCPtr(oldPtr));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public virtual SWIGTYPE_p_void getUniquePointer(SWIGTYPE_p_void oldPtr) {
    global::System.IntPtr cPtr = BulletPINVOKE.btSerializer_getUniquePointer(swigCPtr, SWIGTYPE_p_void.getCPtr(oldPtr));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public virtual void startSerialization() {
    BulletPINVOKE.btSerializer_startSerialization(swigCPtr);
  }

  public virtual void finishSerialization() {
    BulletPINVOKE.btSerializer_finishSerialization(swigCPtr);
  }

  public virtual string findNameForPointer(SWIGTYPE_p_void ptr) {
    string ret = BulletPINVOKE.btSerializer_findNameForPointer(swigCPtr, SWIGTYPE_p_void.getCPtr(ptr));
    return ret;
  }

  public virtual void registerNameForPointer(SWIGTYPE_p_void ptr, string name) {
    BulletPINVOKE.btSerializer_registerNameForPointer(swigCPtr, SWIGTYPE_p_void.getCPtr(ptr), name);
  }

  public virtual void serializeName(string ptr) {
    BulletPINVOKE.btSerializer_serializeName(swigCPtr, ptr);
  }

  public virtual int getSerializationFlags() {
    int ret = BulletPINVOKE.btSerializer_getSerializationFlags(swigCPtr);
    return ret;
  }

  public virtual void setSerializationFlags(int flags) {
    BulletPINVOKE.btSerializer_setSerializationFlags(swigCPtr, flags);
  }

}

}
