//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btSliderConstraintDoubleData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btSliderConstraintDoubleData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btSliderConstraintDoubleData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btSliderConstraintDoubleData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btSliderConstraintDoubleData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btTypedConstraintDoubleData m_typeConstraintData {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_typeConstraintData_set(swigCPtr, btTypedConstraintDoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btSliderConstraintDoubleData_m_typeConstraintData_get(swigCPtr);
      btTypedConstraintDoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btTypedConstraintDoubleData(cPtr, false);
      return ret;
    } 
  }

  public btTransformDoubleData m_rbAFrame {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_rbAFrame_set(swigCPtr, btTransformDoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btSliderConstraintDoubleData_m_rbAFrame_get(swigCPtr);
      btTransformDoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btTransformDoubleData(cPtr, false);
      return ret;
    } 
  }

  public btTransformDoubleData m_rbBFrame {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_rbBFrame_set(swigCPtr, btTransformDoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btSliderConstraintDoubleData_m_rbBFrame_get(swigCPtr);
      btTransformDoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btTransformDoubleData(cPtr, false);
      return ret;
    } 
  }

  public double m_linearUpperLimit {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_linearUpperLimit_set(swigCPtr, value);
    } 
    get {
      double ret = BulletPINVOKE.btSliderConstraintDoubleData_m_linearUpperLimit_get(swigCPtr);
      return ret;
    } 
  }

  public double m_linearLowerLimit {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_linearLowerLimit_set(swigCPtr, value);
    } 
    get {
      double ret = BulletPINVOKE.btSliderConstraintDoubleData_m_linearLowerLimit_get(swigCPtr);
      return ret;
    } 
  }

  public double m_angularUpperLimit {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_angularUpperLimit_set(swigCPtr, value);
    } 
    get {
      double ret = BulletPINVOKE.btSliderConstraintDoubleData_m_angularUpperLimit_get(swigCPtr);
      return ret;
    } 
  }

  public double m_angularLowerLimit {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_angularLowerLimit_set(swigCPtr, value);
    } 
    get {
      double ret = BulletPINVOKE.btSliderConstraintDoubleData_m_angularLowerLimit_get(swigCPtr);
      return ret;
    } 
  }

  public int m_useLinearReferenceFrameA {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_useLinearReferenceFrameA_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btSliderConstraintDoubleData_m_useLinearReferenceFrameA_get(swigCPtr);
      return ret;
    } 
  }

  public int m_useOffsetForConstraintFrame {
    set {
      BulletPINVOKE.btSliderConstraintDoubleData_m_useOffsetForConstraintFrame_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btSliderConstraintDoubleData_m_useOffsetForConstraintFrame_get(swigCPtr);
      return ret;
    } 
  }

  public btSliderConstraintDoubleData() : this(BulletPINVOKE.new_btSliderConstraintDoubleData(), true) {
  }

}

}
