//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btStridingMeshInterfaceData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btStridingMeshInterfaceData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btStridingMeshInterfaceData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btStridingMeshInterfaceData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btStridingMeshInterfaceData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btMeshPartData m_meshPartsPtr {
    set {
      BulletPINVOKE.btStridingMeshInterfaceData_m_meshPartsPtr_set(swigCPtr, btMeshPartData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btStridingMeshInterfaceData_m_meshPartsPtr_get(swigCPtr);
      btMeshPartData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btMeshPartData(cPtr, false);
      return ret;
    } 
  }

  public btVector3FloatData m_scaling {
    set {
      BulletPINVOKE.btStridingMeshInterfaceData_m_scaling_set(swigCPtr, btVector3FloatData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btStridingMeshInterfaceData_m_scaling_get(swigCPtr);
      btVector3FloatData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3FloatData(cPtr, false);
      return ret;
    } 
  }

  public int m_numMeshParts {
    set {
      BulletPINVOKE.btStridingMeshInterfaceData_m_numMeshParts_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btStridingMeshInterfaceData_m_numMeshParts_get(swigCPtr);
      return ret;
    } 
  }

  public string m_padding {
    set {
      BulletPINVOKE.btStridingMeshInterfaceData_m_padding_set(swigCPtr, value);
    } 
    get {
      string ret = BulletPINVOKE.btStridingMeshInterfaceData_m_padding_get(swigCPtr);
      return ret;
    } 
  }

  public btStridingMeshInterfaceData() : this(BulletPINVOKE.new_btStridingMeshInterfaceData(), true) {
  }

}

}
