//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btStaticPlaneShapeData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btStaticPlaneShapeData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btStaticPlaneShapeData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btStaticPlaneShapeData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btStaticPlaneShapeData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btCollisionShapeData m_collisionShapeData {
    set {
      BulletPINVOKE.btStaticPlaneShapeData_m_collisionShapeData_set(swigCPtr, btCollisionShapeData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btStaticPlaneShapeData_m_collisionShapeData_get(swigCPtr);
      btCollisionShapeData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btCollisionShapeData(cPtr, false);
      return ret;
    } 
  }

  public btVector3FloatData m_localScaling {
    set {
      BulletPINVOKE.btStaticPlaneShapeData_m_localScaling_set(swigCPtr, btVector3FloatData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btStaticPlaneShapeData_m_localScaling_get(swigCPtr);
      btVector3FloatData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3FloatData(cPtr, false);
      return ret;
    } 
  }

  public btVector3FloatData m_planeNormal {
    set {
      BulletPINVOKE.btStaticPlaneShapeData_m_planeNormal_set(swigCPtr, btVector3FloatData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btStaticPlaneShapeData_m_planeNormal_get(swigCPtr);
      btVector3FloatData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3FloatData(cPtr, false);
      return ret;
    } 
  }

  public float m_planeConstant {
    set {
      BulletPINVOKE.btStaticPlaneShapeData_m_planeConstant_set(swigCPtr, value);
    } 
    get {
      float ret = BulletPINVOKE.btStaticPlaneShapeData_m_planeConstant_get(swigCPtr);
      return ret;
    } 
  }

  public string m_pad {
    set {
      BulletPINVOKE.btStaticPlaneShapeData_m_pad_set(swigCPtr, value);
    } 
    get {
      string ret = BulletPINVOKE.btStaticPlaneShapeData_m_pad_get(swigCPtr);
      return ret;
    } 
  }

  public btStaticPlaneShapeData() : this(BulletPINVOKE.new_btStaticPlaneShapeData(), true) {
  }

}

}
