//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BulletSharp {

public class btTypedConstraintDoubleData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal btTypedConstraintDoubleData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btTypedConstraintDoubleData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~btTypedConstraintDoubleData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BulletPINVOKE.delete_btTypedConstraintDoubleData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public btRigidBodyDoubleData m_rbA {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_rbA_set(swigCPtr, btRigidBodyDoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btTypedConstraintDoubleData_m_rbA_get(swigCPtr);
      btRigidBodyDoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btRigidBodyDoubleData(cPtr, false);
      return ret;
    } 
  }

  public btRigidBodyDoubleData m_rbB {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_rbB_set(swigCPtr, btRigidBodyDoubleData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BulletPINVOKE.btTypedConstraintDoubleData_m_rbB_get(swigCPtr);
      btRigidBodyDoubleData ret = (cPtr == global::System.IntPtr.Zero) ? null : new btRigidBodyDoubleData(cPtr, false);
      return ret;
    } 
  }

  public string m_name {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_name_set(swigCPtr, value);
    } 
    get {
      string ret = BulletPINVOKE.btTypedConstraintDoubleData_m_name_get(swigCPtr);
      return ret;
    } 
  }

  public int m_objectType {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_objectType_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btTypedConstraintDoubleData_m_objectType_get(swigCPtr);
      return ret;
    } 
  }

  public int m_userConstraintType {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_userConstraintType_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btTypedConstraintDoubleData_m_userConstraintType_get(swigCPtr);
      return ret;
    } 
  }

  public int m_userConstraintId {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_userConstraintId_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btTypedConstraintDoubleData_m_userConstraintId_get(swigCPtr);
      return ret;
    } 
  }

  public int m_needsFeedback {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_needsFeedback_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btTypedConstraintDoubleData_m_needsFeedback_get(swigCPtr);
      return ret;
    } 
  }

  public double m_appliedImpulse {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_appliedImpulse_set(swigCPtr, value);
    } 
    get {
      double ret = BulletPINVOKE.btTypedConstraintDoubleData_m_appliedImpulse_get(swigCPtr);
      return ret;
    } 
  }

  public double m_dbgDrawSize {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_dbgDrawSize_set(swigCPtr, value);
    } 
    get {
      double ret = BulletPINVOKE.btTypedConstraintDoubleData_m_dbgDrawSize_get(swigCPtr);
      return ret;
    } 
  }

  public int m_disableCollisionsBetweenLinkedBodies {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_disableCollisionsBetweenLinkedBodies_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btTypedConstraintDoubleData_m_disableCollisionsBetweenLinkedBodies_get(swigCPtr);
      return ret;
    } 
  }

  public int m_overrideNumSolverIterations {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_overrideNumSolverIterations_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btTypedConstraintDoubleData_m_overrideNumSolverIterations_get(swigCPtr);
      return ret;
    } 
  }

  public double m_breakingImpulseThreshold {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_breakingImpulseThreshold_set(swigCPtr, value);
    } 
    get {
      double ret = BulletPINVOKE.btTypedConstraintDoubleData_m_breakingImpulseThreshold_get(swigCPtr);
      return ret;
    } 
  }

  public int m_isEnabled {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_m_isEnabled_set(swigCPtr, value);
    } 
    get {
      int ret = BulletPINVOKE.btTypedConstraintDoubleData_m_isEnabled_get(swigCPtr);
      return ret;
    } 
  }

  public string padding {
    set {
      BulletPINVOKE.btTypedConstraintDoubleData_padding_set(swigCPtr, value);
    } 
    get {
      string ret = BulletPINVOKE.btTypedConstraintDoubleData_padding_get(swigCPtr);
      return ret;
    } 
  }

  public btTypedConstraintDoubleData() : this(BulletPINVOKE.new_btTypedConstraintDoubleData(), true) {
  }

}

}
